--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/quydrop/DROP-ClearLagSystem
build-by-default: true
branches:
- main
projects:
  DROP-ClearLagSystem:
    path: ""
    icon: "https://avatars.githubusercontent.com/u/30586899?s=1080&v=4"
...
